name: Cross-platform CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  call-linux:
    uses: ./.github/workflows/linux.yml
    secrets: inherit
  call-windows:
    uses: ./.github/workflows/windows.yml
    secrets: inherit
  call-doxygen-gh-pages:
    if: success() && github.event.push == true
    uses: ./.github/workflows/doxygen-gh-pages.yml
