name: Doxygen GitHub Pages Deploy Action

on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
          submodules: recursive

      - name: Configure git
        run: |
          git config --global user.name Github Actions
          git config --global user.emale actions@github.com
          git config --global pull.rebase false

      - name: Fetch main branch
        run: git fetch origin main

      - name: Checkout source files
        run: git checkout main -- src examples memory

      - uses: DenverCoder1/doxygen-github-pages-action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/html
          config_file: doxyconf
          doxygen_version: 1.11.0
