name: Makefile CI

on:
  push:
    branches: [ "win" ]
  pull_request:
    branches: [ "win" ]

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          curl
          git
          mingw-w64-check
          autoconf-archive

    - run: git config --global core.autocrlf input
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Pull & update submodules recursively
      run: |
        git submodule update --init --recursive
        git submodule update --recursive --remote

    - name: Regenerate build files
      run: ./autogen.sh

    - name: configure
      run: ./configure CFLAGS='-Wall -Wextra -Wno-override-init -O2'

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run valgrind check
      run: make check-valgrind

    - name: Archive test logs
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: check-logs
        path: |
          *.log
          tests/*.log
        retention-days: 5

    - name: Run distcheck
      run: make distcheck
