name: Makefile CI

on:
  push:
    branches: [ "main", "mingw" ]
  pull_request:
    branches: [ "main", "mingw" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: autoconf-archive mingw-w64 mingw-w64-common mingw-w64-x86-64-dev valgrind check
        version: 1.0

    - name: Pull & update submodules recursively
      run: |
        git submodule update --init --recursive
        git submodule update --recursive --remote

    - name: Regenerate build files
      run: ./autogen.sh

    - name: Install dependencies
      run: make

    - name: Run check
      run: make check

    - name: Run valgrind check
      run: make check-valgrind

    - name: Archive test logs
      uses: actions/upload-artifact@v4
      with:
        name: check-logs
        path: tests/*.log
        retention-days: 5

    - name: Run distcheck
      run: make distcheck
