name: Render Readme

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAGES_DEPLOYMENT_TOKEN }}

      - name: Download statuses
        uses: actions/download-artifact@v4
        with:
          name: statuses

      - name: Render README.md
        run: echo "... Rendering ..."

      - name: Configure Git
        run: |
          git config --global user.name Github Actions
          git config --global user.email actions@github.com

      - name: Update push README.md
        run: |
          git add README.md
          git diff --staged --quiet && \
            (echo "No changes in README.md.") || \
            (git commit -m "[skip ci] Update README.md" && git push)
