name: Resolve tag files

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAGES_DEPLOYMENT_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name Github Actions
          git config --global user.gmail actions@github.com

      - name: Update vector.tag
        run: |
          wget https://evjeesm.github.io/vector/vector.tag
          git add -f vector.tag
          git commit -m "[skip ci] Update tagfile in main"
          git push
